[package]
name = "either"
version = "0.1.0"
authors = ["Mark Meredith <mark.meredith@netl.doe.gov>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
